version: '3'
services:

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999

  contas:
    image: 'zupacademy/contas'
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888

#  transacoes:
#      image: 'zupacademy/transacoes'
#      ports:
#        - 7777:7777
#      environment:
#        SERVER_PORT: 7777

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    image: jboss/keycloak
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
#      - grafana
#      - prometheus
#      - jaeger
#      - kafka
#      - zookeeper
      - contas
      - analise
#      - transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1

volumes:
  postgres-volume: